In [3]:
import pandas as pd
df = pd.read_excel("Bonneville Data.xlsx", "Bonneville 1-1-1960 to 12-31-20")
df

,Dam,Date,ChinAdult,ChinJack,CohoAdult,CohoJack,Steelhead,WildSteelhead,Sockeye,Pink,Chum,Lamprey,Shad
0,BON,1960-03-01,0,0,0,0,0,0,0,0,0,0,0
1,BON,1960-03-02,0,0,0,0,0,0,0,0,0,0,0
2,BON,1960-03-03,0,0,0,0,2,0,0,0,0,0,0
3,BON,1960-03-04,0,0,0,0,0,0,0,0,0,0,0
4,BON,1960-03-05,0,0,0,0,5,0,0,0,0,0,0
5,BON,1960-03-06,0,0,0,0,0,0,0,0,0,0,0
6,BON,1960-03-07,0,0,0,0,0,0,0,0,0,0,0
7,BON,1960-03-08,0,0,0,0,0,0,0,0,0,0,0
8,BON,1960-03-09,0,0,0,0,0,0,0,0,0,0,0
9,BON,1960-03-10,0,0,0,0,0,0,0,0,0,0,0
10,BON,1960-03-11,0,0,0,0,0,0,0,0,0,0,0
11,BON,1960-03-12,0,0,0,0,0,0,0,0,0,0,0
12,BON,1960-03-13,2,0,0,0,2,0,0,0,0,0,0
13,BON,1960-03-14,0,0,0,0,2,0,0,0,0,0,0
14,BON,1960-03-15,0,0,0,0,5,0,0,0,0,0,0
15,BON,1960-03-16,0,0,0,0,4,0,0,0,0,0,0
16,BON,1960-03-17,4,0,0,0,12,0,0,0,0,0,0
17,BON,1960-03-18,7,0,0,0,9,0,0,0,0,0,0
18,BON,1960-03-19,9,0,0,0,15,0,0,0,0,0,0
19,BON,1960-03-20,7,0,0,0,44,0,0,0,0,0,0
20,BON,1960-03-21,2,0,0,0,36,0,0,0,0,0,0
21,BON,1960-03-22,9,0,0,0,17,0,0,0,0,0,0
22,BON,1960-03-23,16,0,0,0,32,0,0,0,0,0,0
23,BON,1960-03-24,30,0,0,0,42,0,0,0,0,0,0
24,BON,1960-03-25,42,0,0,0,62,0,0,0,0,0,0
25,BON,1960-03-26,11,0,0,0,34,0,0,0,0,0,0
26,BON,1960-03-27,20,0,0,0,30,0,0,0,0,0,0
27,BON,1960-03-28,7,0,0,0,10,0,0,0,0,0,0
28,BON,1960-03-29,7,0,0,0,23,0,0,0,0,0,0
29,BON,1960-03-30,9,0,0,0,19,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15796,BON,2015-12-02,9,3,15,0,57,18,0,0,0,0,0
15797,BON,2015-12-03,12,0,12,0,41,14,0,0,0,-1,0
15798,BON,2015-12-04,16,3,2,0,29,9,0,0,0,0,0
15799,BON,2015-12-05,0,1,11,0,38,15,0,0,0,0,0
15800,BON,2015-12-06,16,0,26,1,36,11,0,0,0,0,0
15801,BON,2015-12-07,9,3,48,1,85,27,0,0,0,1,0
15802,BON,2015-12-08,8,1,34,2,50,18,0,0,0,5,0
15803,BON,2015-12-09,2,0,4,0,11,1,0,0,0,3,0
15804,BON,2015-12-10,3,1,6,0,8,3,0,0,0,-6,0
15805,BON,2015-12-11,4,0,3,0,22,9,0,0,0,0,0
15806,BON,2015-12-12,12,3,15,0,60,23,0,0,0,0,0
15807,BON,2015-12-13,14,1,-2,0,69,29,0,0,0,0,0
15808,BON,2015-12-14,5,3,4,0,71,36,0,0,0,0,0
15809,BON,2015-12-15,3,2,6,0,77,32,0,0,0,0,0
15810,BON,2015-12-16,0,3,1,0,40,12,0,0,0,0,0
15811,BON,2015-12-17,2,0,2,0,32,13,0,0,0,0,0
15812,BON,2015-12-18,2,0,1,0,31,13,0,0,0,0,0
15813,BON,2015-12-19,2,0,0,0,33,11,0,0,0,0,0
15814,BON,2015-12-20,2,0,1,0,40,14,0,0,0,0,0
15815,BON,2015-12-21,2,0,2,0,26,7,0,0,0,0,0
15816,BON,2015-12-22,0,0,7,0,56,16,0,0,0,0,0
15817,BON,2015-12-23,1,0,-2,0,46,10,0,0,0,0,0
15818,BON,2015-12-24,1,1,-1,0,35,10,0,0,0,0,0
15819,BON,2015-12-25,4,1,1,0,44,24,0,0,0,0,0
15820,BON,2015-12-26,0,0,0,0,43,10,0,0,0,0,0
15821,BON,2015-12-27,0,2,0,0,30,7,0,0,0,0,0
15822,BON,2015-12-28,1,0,-1,0,26,6,0,0,0,0,0
15823,BON,2015-12-29,1,0,0,0,15,10,0,0,0,0,0
15824,BON,2015-12-30,1,0,0,0,30,8,0,0,0,0,0
15825,BON,2015-12-31,1,0,0,0,40,10,0,0,0,0,0

#### Question 1: What is the average number of sightings by species, total?

In [4]:
df.mean()

ChinAdult        1566.151776
ChinJack          187.441994
CohoAdult         228.331922
CohoJack           18.350120
Steelhead         844.748326
WildSteelhead     127.902313
Sockeye           380.769556
Pink                0.445217
Chum                0.564261
Lamprey           138.256477
Shad             5224.860799
dtype: float64

#### Question 2: What is the average number of sighting by species up until 1980?

In [20]:
df['Date'] = pd.to_datetime(df.Date)
ts = pd.to_datetime('1/1/1981')
df.loc[df['Date'] < ts].mean()

ChinAdult        1368.401176
ChinJack            6.933872
CohoAdult         188.171749
CohoJack            1.667524
Steelhead         529.742101
WildSteelhead       0.000000
Sockeye           264.126929
Pink                0.206098
Chum                1.214732
Lamprey           288.022410
Shad             1598.746877
dtype: float64

#### Question 3: What were the max number sightings for each species in 1972?

In [31]:
df.loc[df.Date.dt.year == 1972].describe()

,ChinAdult,ChinJack,CohoAdult,CohoJack,Steelhead,WildSteelhead,Sockeye,Pink,Chum,Lamprey,Shad
count,244.000000,244.0,244.000000,244.0,244.000000,244.0,244.000000,244.000000,244.000000,244.0,244.000000
mean,1616.622951,0.0,270.213115,0.0,761.827869,0.0,230.831967,0.209016,0.004098,0.0,880.020492
std,2788.952490,0.0,679.472038,0.0,1116.090064,0.0,656.987438,0.930375,0.064018,0.0,2772.857041
min,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000
25%,136.000000,0.0,0.000000,0.0,48.750000,0.0,0.000000,0.000000,0.000000,0.0,0.000000
50%,632.500000,0.0,0.000000,0.0,114.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000
75%,1528.250000,0.0,105.250000,0.0,1257.750000,0.0,48.500000,0.000000,0.000000,0.0,54.000000
max,19241.000000,0.0,3774.000000,0.0,5359.000000,0.0,4000.000000,9.000000,1.000000,0.0,19490.000000

#### Question 4: What days had the greatest sightings of Steelhead in 1960?

In [36]:
df.loc[df.Date.dt.year == 1960].sort_values(['Steelhead'], ascending=False)

,Dam,Date,ChinAdult,ChinJack,CohoAdult,CohoJack,Steelhead,WildSteelhead,Sockeye,Pink,Chum,Lamprey,Shad
146,BON,1960-07-25,1545,0,0,0,4816,0,316,0,0,9205,1094
149,BON,1960-07-28,939,0,0,0,4428,0,107,0,0,16517,216
143,BON,1960-07-22,730,0,0,0,4011,0,386,0,0,3869,696
147,BON,1960-07-26,1079,0,0,0,3645,0,244,0,0,6912,1261
148,BON,1960-07-27,968,0,0,0,3581,0,167,0,0,16912,314
142,BON,1960-07-21,1019,0,0,0,2870,0,312,0,0,7670,1136
150,BON,1960-07-29,996,0,0,0,2868,0,89,0,0,6843,356
153,BON,1960-08-01,491,0,0,0,2442,0,38,0,0,1239,187
190,BON,1960-09-07,7095,0,220,0,2361,0,0,0,0,820,68
151,BON,1960-07-30,563,0,0,0,2265,0,40,0,0,4497,284
188,BON,1960-09-05,7848,0,269,0,2210,0,0,0,0,296,0
141,BON,1960-07-20,912,0,0,0,2167,0,343,0,0,6332,1514
193,BON,1960-09-10,5333,0,152,0,2028,0,0,0,0,85,0
145,BON,1960-07-24,565,0,0,0,1976,0,214,0,0,1664,425
144,BON,1960-07-23,893,0,0,0,1946,0,210,0,0,2167,611
183,BON,1960-08-31,3974,0,236,0,1879,0,0,0,0,518,0
194,BON,1960-09-11,4112,0,143,0,1773,0,2,0,0,182,0
192,BON,1960-09-09,3651,0,116,0,1738,0,0,0,0,711,2
186,BON,1960-09-03,6400,0,137,0,1681,0,2,0,0,449,0
187,BON,1960-09-04,5395,0,285,0,1648,0,7,0,0,576,0
185,BON,1960-09-02,4586,0,85,0,1596,0,0,0,0,185,0
184,BON,1960-09-01,4086,0,78,0,1569,0,0,0,0,248,0
189,BON,1960-09-06,5151,0,233,0,1560,0,0,0,0,402,0
191,BON,1960-09-08,5198,0,235,0,1552,0,0,0,0,871,0
182,BON,1960-08-30,3050,0,91,0,1539,0,2,0,0,584,0
163,BON,1960-08-11,366,0,0,0,1433,0,2,0,0,932,8
181,BON,1960-08-29,2621,0,119,0,1410,0,0,0,0,385,6
154,BON,1960-08-02,452,0,0,0,1398,0,38,0,0,2249,80
155,BON,1960-08-03,320,0,0,0,1376,0,35,0,0,1794,60
162,BON,1960-08-10,425,0,0,0,1363,0,5,0,0,2438,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,BON,1960-11-27,0,0,0,0,2,0,0,0,0,0,0
268,BON,1960-11-24,4,0,0,0,2,0,0,0,24,0,0
259,BON,1960-11-15,7,0,0,0,2,0,0,0,34,0,0
267,BON,1960-11-23,0,0,0,0,2,0,0,0,24,0,0
263,BON,1960-11-19,2,0,0,0,2,0,0,0,27,0,0
252,BON,1960-11-08,2,0,0,0,2,0,0,0,31,0,0
264,BON,1960-11-20,0,0,0,0,2,0,0,0,17,0,0
12,BON,1960-03-13,2,0,0,0,2,0,0,0,0,0,0
272,BON,1960-11-28,5,0,0,0,2,0,0,0,2,0,0
46,BON,1960-04-16,328,0,0,0,2,0,0,0,0,0,0
2,BON,1960-03-03,0,0,0,0,2,0,0,0,0,0,0
238,BON,1960-10-25,45,0,5,0,2,0,0,0,29,0,0
75,BON,1960-05-15,191,0,0,0,2,0,0,0,0,3,0
80,BON,1960-05-20,31,0,0,0,2,0,0,0,0,3,0
81,BON,1960-05-21,11,0,0,0,2,0,0,0,0,8,0
3,BON,1960-03-04,0,0,0,0,0,0,0,0,0,0,0
270,BON,1960-11-26,4,0,0,0,0,0,0,0,0,0,0
269,BON,1960-11-25,0,0,0,0,0,0,0,0,0,0,0
266,BON,1960-11-22,0,0,0,0,0,0,0,0,0,0,0
1,BON,1960-03-02,0,0,0,0,0,0,0,0,0,0,0
11,BON,1960-03-12,0,0,0,0,0,0,0,0,0,0,0
5,BON,1960-03-06,0,0,0,0,0,0,0,0,0,0,0
6,BON,1960-03-07,0,0,0,0,0,0,0,0,0,0,0
7,BON,1960-03-08,0,0,0,0,0,0,0,0,0,0,0
8,BON,1960-03-09,0,0,0,0,0,0,0,0,0,0,0
9,BON,1960-03-10,0,0,0,0,0,0,0,0,0,0,0
10,BON,1960-03-11,0,0,0,0,0,0,0,0,0,0,0
45,BON,1960-04-15,230,0,0,0,0,0,0,0,0,0,0
47,BON,1960-04-17,212,0,0,0,0,0,0,0,0,0,0
0,BON,1960-03-01,0,0,0,0,0,0,0,0,0,0,0